language: php

php:
    - '7.0'
    - nightly

addon:
    mariadb: '10.0'
    code_climate:
        repo_token: 5a4ff4f02239eed7f0c6c32b9cc6774ef7e46168d682f53e51a98f82574f254e

before_install:
    - mysql -e "create database IF NOT EXISTS baddeed_test;" -uroot
    - mysql -e "create user deed_test;" -uroot
    - mysql -e "grant all privileges on baddeed_test.* to deed_test@'localhost' identified by 'deed_test'" -uroot
    - mysql -e "flush privileges;" -uroot
    - mysql -u root baddeed_test < setup/db/create.sql 

install:
    - composer install

script:
    - phpunit

